version: '3'
services:
  database:
    image: 'postgres'
    container_name: 'squad_up_db'
    ports:
      - 5432:5432
    env_file:
      - database.env
    volumes:
      - squadup-data:/var/lib/postgresql/data/

volumes:
  squadup-data:
    external: true